### PR TITLE
Dimitroff

### PR DESCRIPTION
**Pull request by dimitroff2**
# Description
I completed the trello tile for "View All Categories"
Created code so a list of available Categories would be accessible to a logged in user. A user should be able to view all Categories in database, displayed in alphabetical order.

Fixes # 
No fixes first time adding this information

_Note: Create/Edit/Delete/Details are non-functioning and will be on additional PRs_

Created the following files and methods:
File for CategoryController.cs in controllers folder
File for Index in Views>Category> index.cshtml
Added link in sharedLayout.cshtml for Category Management

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# Testing Instructions

Reference  [How to test a teammate's PR](https://gist.github.com/jordan-castelloe/96f76d5bd4cfbd2181084af674c2a1af#when-you-need-to-test-a-teammates-pr)

Log in using admin@example.com
Make sure to add all [seed data](https://github.com/NewForce-Cohort-5/tabloidmvc-the-runtime-terrors/tree/main/SQL) before testing
Click on Category Management in NavBar
View the list of available Categories (categories should appear in alphabetical order)
There should be column with the Name and next to each name a link to edit details and delete, these are not yet functional.
Available list of categories :
Cooking, Cthulhu Sightings, Entertainment, History, Home and Garden, Improv, Movies, Music, Politics, Regrets, Science, Technology

### CODE REVIEW

**Comment by sarahebrooks12** [comment]
Testing instructions are lacking. Need to know everything that I would need to do to properly test this feature. How do I log in? Where do I get the data? What categories should I be seeing? Is there a SQL query that I should utilize to double check everything is correct? Please look at closed pull requests for examples

**Comment by sarahebrooks12** [comment]
No links are active in testing instructions. What are the categories I should be verifying? Is there a SQL query or a list of those categories that I can utilize as a comparsion?

**Comment by sarahebrooks12** [comment]
👼

**Comment by helloamandaball** [comment]
🐱 Cat-egory is displaying correct! The only thing is I'm not sure we actually need to see the category ID column in browser. Other than that, it's good to go.

**Review by jonahamoore — APPROVED** [review]
looks guuud

**Review by bdigregs — APPROVED** [review]
Aw yeah, darn right

**Pull request merged**
