### PR TITLE
Jam view current users post

### PR DESCRIPTION
**Pull request by jonahamoore**
Trello Ticket: [#4 - View Current User's Post]
Created code to allow a logged in user to create a new post and view that post under a personal section of the webpage called My Post that only displays the current users posts in order of most recent post

Created the following files and methods:

Created a MyPost.cshtml view file that contains each property we want to display that also orders the post by date.
PostController now has a MyPost view that grabs each individual persons posts by id and displays it.
Post Repository contains a method of GetAllIndividual posts that fetches the user's post based on their UserProfileId.

Recent EDIT: changed the mypost file to order by date, previous push had dates in random order.

Type of change
 New feature (non-breaking change which adds functionality).
 This change requires a documentation update.

Testing Instructions
Reference [How to test a teammate's PR](https://gist.github.com/jordan-castelloe/96f76d5bd4cfbd2181084af674c2a1af#when-you-need-to-test-a-teammates-pr)
Login using the new name you created, the number 2 on the last line of the SQL query indicates you are an author not admin.
You can add yourself as a user in the SQL database by running this command, just change my name out for yours or just choose to use my name as an example.
--Insert Into UserProfile (DisplayName, FirstName, LastName, Email, CreateDateTime, ImageLocation, UserTypeId)
--Values ('JonahMoore', 'Jonah', 'Moore', 'jonah@example.com', 2022-03-03, null, 2);
--Select * From UserProfile (should see all the info)
Make sure to add all [seed data](https://github.com/NewForce-Cohort-5/tabloidmvc-the-runtime-terrors/tree/main/SQL) before testing

Click on MyPost in NavBar
View the list of your own posts, you can also create them here as well and when you do they should appear in order of the created date time, with the only categories of title, displayname, category, and createdatetime showing on the page. To ensure it is working compare the Posts page to the My Post page. You should NOT see the admin's c# post on your My Post page because your created login is an author not an admin and you didn't create the post.

### CODE REVIEW

**Comment by sarahebrooks12** [comment]
SO CLOSE --- What would show the tester that it is working? *specifically*

**Review by bdigregs — APPROVED** [review]
Works

**Comment by sarahebrooks12** [comment]
👼

**Review by helloamandaball — APPROVED** [review]
👍 working

**Pull request merged**
